/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.crio.qcalc;

public class App {
    public String getGreeting() {
        return "Welcome to QCalc";
    }

    public static void main(String[] args) {
        System.out.println("Starting QCalc...");
        System.out.println(new App().getGreeting());

        StandardCalculator calc = new StandardCalculator();
        StandardCalculator.getVersion();

        calc.add(10, 2);
        calc.printResult();

        calc.subtract(10, 2);
        calc.printResult();

        calc.multiply(10, 2);
        calc.printResult();

        calc.divide(10, 2);
        calc.printResult();

        calc.clearResult();
        calc.printResult();

        ScientificCalculator sciCalc = new ScientificCalculator();
        ScientificCalculator.getVersion();

        System.out.println("squareOf: " + sciCalc.squareOf(5.0));
        System.out.println("cubeOf: " + sciCalc.cubeOf(4.0));
        System.out.println("powerOf: " + sciCalc.powerOf(2.0, 8.0));
        System.out.println("squareRoot: " + sciCalc.squareRoot(625.0));
        System.out.println("modulo: " + sciCalc.modulo(5, 2));
        System.out.println("modulo double: " + sciCalc.modulo_double(5.0, 2.0));
    }
}
